/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardSkillGapRouteImport } from './routes/_authenticated/dashboard.skill-gap'
import { Route as AuthenticatedDashboardRoadmapsRouteImport } from './routes/_authenticated/dashboard.roadmaps'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardCompanyFitRouteImport } from './routes/_authenticated/dashboard.company-fit'
import { Route as AuthenticatedDashboardCoachRouteImport } from './routes/_authenticated/dashboard.coach'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSkillGapRoute =
  AuthenticatedDashboardSkillGapRouteImport.update({
    id: '/skill-gap',
    path: '/skill-gap',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRoadmapsRoute =
  AuthenticatedDashboardRoadmapsRouteImport.update({
    id: '/roadmaps',
    path: '/roadmaps',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCompanyFitRoute =
  AuthenticatedDashboardCompanyFitRouteImport.update({
    id: '/company-fit',
    path: '/company-fit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCoachRoute =
  AuthenticatedDashboardCoachRouteImport.update({
    id: '/coach',
    path: '/coach',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/coach': typeof AuthenticatedDashboardCoachRoute
  '/dashboard/company-fit': typeof AuthenticatedDashboardCompanyFitRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/roadmaps': typeof AuthenticatedDashboardRoadmapsRoute
  '/dashboard/skill-gap': typeof AuthenticatedDashboardSkillGapRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/coach': typeof AuthenticatedDashboardCoachRoute
  '/dashboard/company-fit': typeof AuthenticatedDashboardCompanyFitRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/roadmaps': typeof AuthenticatedDashboardRoadmapsRoute
  '/dashboard/skill-gap': typeof AuthenticatedDashboardSkillGapRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/coach': typeof AuthenticatedDashboardCoachRoute
  '/_authenticated/dashboard/company-fit': typeof AuthenticatedDashboardCompanyFitRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/roadmaps': typeof AuthenticatedDashboardRoadmapsRoute
  '/_authenticated/dashboard/skill-gap': typeof AuthenticatedDashboardSkillGapRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/coach'
    | '/dashboard/company-fit'
    | '/dashboard/profile'
    | '/dashboard/roadmaps'
    | '/dashboard/skill-gap'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/coach'
    | '/dashboard/company-fit'
    | '/dashboard/profile'
    | '/dashboard/roadmaps'
    | '/dashboard/skill-gap'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/coach'
    | '/_authenticated/dashboard/company-fit'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/roadmaps'
    | '/_authenticated/dashboard/skill-gap'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/skill-gap': {
      id: '/_authenticated/dashboard/skill-gap'
      path: '/skill-gap'
      fullPath: '/dashboard/skill-gap'
      preLoaderRoute: typeof AuthenticatedDashboardSkillGapRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/roadmaps': {
      id: '/_authenticated/dashboard/roadmaps'
      path: '/roadmaps'
      fullPath: '/dashboard/roadmaps'
      preLoaderRoute: typeof AuthenticatedDashboardRoadmapsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/company-fit': {
      id: '/_authenticated/dashboard/company-fit'
      path: '/company-fit'
      fullPath: '/dashboard/company-fit'
      preLoaderRoute: typeof AuthenticatedDashboardCompanyFitRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/coach': {
      id: '/_authenticated/dashboard/coach'
      path: '/coach'
      fullPath: '/dashboard/coach'
      preLoaderRoute: typeof AuthenticatedDashboardCoachRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCoachRoute: typeof AuthenticatedDashboardCoachRoute
  AuthenticatedDashboardCompanyFitRoute: typeof AuthenticatedDashboardCompanyFitRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardRoadmapsRoute: typeof AuthenticatedDashboardRoadmapsRoute
  AuthenticatedDashboardSkillGapRoute: typeof AuthenticatedDashboardSkillGapRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCoachRoute: AuthenticatedDashboardCoachRoute,
    AuthenticatedDashboardCompanyFitRoute:
      AuthenticatedDashboardCompanyFitRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardRoadmapsRoute: AuthenticatedDashboardRoadmapsRoute,
    AuthenticatedDashboardSkillGapRoute: AuthenticatedDashboardSkillGapRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
